name: Compliance

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

permissions:
  pull-requests: write

jobs:
  semantics:
    name: Semantics
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-compliance-checks:
    name: PR Compliance Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: mtfoley/pr-compliance-action@v0.5.0
        with:
          body-auto-close: false
          protected-branch-auto-close: false
          body-regex: '(fix(es|ed)?|resolve(s|d)?|close(s|d)?|related to|relates to|relate to) ((https:\/\/github.com\/[a-zA-Z0-9-_]+\/[a-zA-Z0-9-_]+\/issues\/d*[1-9]d*?)|(#d*[1-9]d*?))'
          watch-files: |
            package.json
            package-lock.json
            npm-shrinkwrap.json
          body-comment: >
            ## Issue Reference

            In order to be considered for merging, the pull request description must refer to a
            specific issue number.

            This check is looking for a phrase similar to: "Fixes #XYZ" or "Relates to #XYZ" where XYZ is the issue
            number that this PR is meant to address.
          protected-branch-comment: >
            ## Protected Branch

            In order to be considered for merging, the pull request changes must
            not be implemented on the "%branch%" branch.

            We would suggest that you close this pull request, create a new branch, implement your changes, and open a new pull request.

  welcome:
    name: Welcome
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: semantics
    if: github.event.action == 'opened'
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |-
            Congratulations on submitting your **first Pull Request**! ðŸŽ‰
            
            We appreciate your contribution. Feel free to join the conversation in our 
            **[Community](https://github.com/orgs/OpenSource-Communities/discussions/4)** and say hello!
